name: Docker Build & Downloadable Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary in Docker
        run: |
          docker run --rm -v "$PWD:/src" -w /src python:3.10-slim bash -c "
            apt update &&
            apt install -y gcc libffi-dev libssl-dev build-essential python3-pip &&
            pip install pyinstaller requests &&
            pyinstaller --onefile fetch_and_run.py &&
            mkdir -p /src/release &&
            cp dist/fetch_and_run /src/release/
          "

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fetch_and_run
          path: release/fetch_and_run
